### ISSUE TITLE
Target directory

### ISSUE THREAD

**Issue by Muzza** [alpine9000/squirt#10]
I'd like to be able to send files from PC to a specified directory within the Amigas Incoming directory.
Currently I have to send the file (via squirt) and then use squirt_exec to MakeDir, Copy, then Delete.
It would be a lot nicer to use a single command like 'squirt <targetIP> <source filename> <destination directory>'

Great project BTW, I'm finding it very useful!

**Comment by alpine9000** [comment]
This commit isn't exactly what you asked for as but it might be better than nothing. squirt now accepts an optional "--dest=blah" argument, however this argument must be an absolute path. I'm not sure if you're building the client stuff yourself, if you're not let me know and I can make a release. There is no change to the squirtd server needed for this.

**Comment by kowoba** [comment]
Thanks, --dest is very useful, I use RAM: as default, and that can be a problem with large files :)

(By combining squirt_exec and squirt in shell scripts or functions, it is now easy to do things like "amiput myfile.lha dh3:downloads/yourfile.lha", where amiput is a script or function, and have destdir path created automatically before the squirt, and file renamed afterwards.)

**Comment by Muzza** [comment]
Sounds great, thanks Alpine. Although I can build the code locally, the releases do make life easier if you get around to it. I'm running it from Windows. I'll try and give it a go soon on my end.

**Comment by alpine9000** [comment]
I ended up creating a v0.3 release that should have this functionality in it.
